Implement AttachmentHandler using AliOSS SDK
halo-sigs/plugin-alioss pull request #2
Opened 2022-08-31 09:02 UTC by JohnNiang

Signed-off-by: johnniang <johnniang@fastmail.com>

2022-09-01 02:20 UTC, ruibaby reviewed
/lgtm

2022-09-02 14:02 UTC, ruibaby requested changes

2022-09-02 14:02 UTC, ruibaby commented on src/main/resources/extensions/policy-template-alioss.yaml
> +      - $formkit: text
```suggestion
      - $formkit: password
```

2022-09-02 14:02 UTC, ruibaby commented on src/main/resources/extensions/policy-template-alioss.yaml
> +      - $formkit: text
```suggestion
      - $formkit: password
```

2022-09-03 16:16 UTC, JohnNiang commented
/release-note-none
/hold
Until https://github.com/halo-dev/halo/pull/2354 got merged.

2022-09-04 12:57 UTC, ruibaby reviewed
/lgtm

2022-09-04 12:58 UTC, guqing reviewed
/approve

2022-09-04 17:06 UTC, JohnNiang commented
/unhold

2022-09-05 02:31 UTC, merged